[build]
  command = "npm install && npm start"
  publish = "server.js"

[dev]
  command = "npm start"
  publish = "server.js"
  functions = "api/"
  environment = { TARGET_URL = "https://test.bilifo.com" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
